### ISSUE TITLE
Scrolling Text Issues

### ISSUE THREAD

**Issue by tldav** [tldav/yoda-horoscope#32]
We need a static button that stays on the text-scroll page after the text finishes scrolling. The static button should link to the horoscope page. 

We'll also need to allow the user to click anywhere on the page to skip the text and go to the static button described above.

**Comment by ghost** [comment]
I know I can create the static button to appear. I'm concerned about the click anywhere function because the user has to push the the audio button, which may trigger the end of the page accidentally. I'll test and let you know what I find out.

**Comment by tldav** [comment]
We went a different route with this.
